# Generated by Django 4.2.13 on 2024-07-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('pr_discription', models.CharField(max_length=200, verbose_name='توضیحات محصول')),
                ('pr_price', models.IntegerField(verbose_name='قیمت')),
                ('pr_photo', models.ImageField(upload_to='photo/', verbose_name='تصویر')),
                ('pr_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shahar.catagory', verbose_name='دسته بندی')),
            ],
        ),
    ]
