# Generated by Django 4.2.13 on 2024-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0003_product_pr_is_sale_product_pr_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=0, max_length=5, verbose_name='ستاره'),
            preserve_default=False,
        ),
    ]
