# Generated by Django 4.2.13 on 2024-07-31 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0004_product_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='ستاره'),
        ),
    ]
