# Generated by Django 4.2.13 on 2024-08-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0005_alter_product_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='نام برند')),
                ('brand_photo', models.ImageField(upload_to=None, verbose_name='تصویر')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, null=True, related_name='brands', to='shahar.brand', verbose_name='برند'),
        ),
    ]
