# Generated by Django 4.2.13 on 2024-08-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0006_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='pr_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_color',
            field=models.ManyToManyField(null=True, to='shahar.color', verbose_name='رنگ'),
        ),
    ]
