# Generated by Django 4.2.13 on 2024-09-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0007_color_rename_brand_product_pr_brand_product_pr_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_color',
            field=models.ManyToManyField(blank=True, null=True, to='shahar.color', verbose_name='رنگ'),
        ),
        migrations.CreateModel(
            name='ProductGalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galary/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shahar.product')),
            ],
        ),
    ]
