# Generated by Django 4.2.13 on 2024-09-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0008_alter_product_pr_color_productgalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgalary',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='productgalary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shahar.product', verbose_name='محصول'),
        ),
    ]
