# Generated by Django 4.2.13 on 2024-09-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0009_productgalary_name_alter_productgalary_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgalary',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
    ]
