# Generated by Django 4.2.13 on 2024-09-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0010_alter_productgalary_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'جدول برند', 'verbose_name_plural': 'برند'},
        ),
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'جدول دسته بندی ها', 'verbose_name_plural': 'دسته بندی '},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'جدول رنگ ها', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'جدول محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productgalary',
            options={'verbose_name': 'گالری تصاویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_brand',
            field=models.ManyToManyField(related_name='brands', to='shahar.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_color',
            field=models.ManyToManyField(to='shahar.color', verbose_name='رنگ'),
        ),
    ]
