# Generated by Django 4.2.13 on 2024-09-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0011_alter_brand_options_alter_catagory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shahar.brand', verbose_name='برند'),
        ),
    ]
