# Generated by Django 4.2.13 on 2024-11-10 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0013_remove_product_pr_brand_product_pr_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='pr_brand',
            field=models.ForeignKey(default='hp', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shahar.brand', verbose_name='برند'),
        ),
    ]
