# Generated by Django 4.2.13 on 2024-11-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0014_remove_product_pr_brand_product_pr_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shahar.brand', verbose_name='برند'),
        ),
    ]
