# Generated by Django 4.2.13 on 2024-11-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0016_remove_product_pr_brand_product_pr_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_brand',
            field=models.ManyToManyField(null=True, related_name='brands', to='shahar.brand', verbose_name='برند'),
        ),
    ]
