# Generated by Django 4.2.13 on 2024-11-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0018_alter_product_pr_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pr_color',
        ),
    ]
