# Generated by Django 4.2.13 on 2024-11-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shahar', '0019_remove_product_pr_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_color',
            field=models.ManyToManyField(to='shahar.color', verbose_name='رنگ'),
        ),
    ]
