# Generated by Django 4.2.13 on 2024-10-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
            ],
        ),
    ]
