# Generated by Django 4.2.13 on 2024-11-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره موبایل'),
        ),
    ]
