# Generated by Django 4.2.13 on 2024-11-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0002_alter_settings_email_alter_settings_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'تنظیمات'},
        ),
    ]
