# Generated by Django 4.2.13 on 2024-11-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0003_alter_settings_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Ttings',
        ),
    ]
