# Generated by Django 4.2.13 on 2024-11-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0004_rename_settings_ttings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttings',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='ttings',
            name='facebook',
            field=models.CharField(default='', max_length=100, verbose_name='فیسبوک'),
        ),
        migrations.AddField(
            model_name='ttings',
            name='insta',
            field=models.CharField(default='', max_length=100, verbose_name='انستاگرام'),
        ),
        migrations.AddField(
            model_name='ttings',
            name='linkedin',
            field=models.CharField(default='', max_length=100, verbose_name='لینکدن'),
        ),
        migrations.AddField(
            model_name='ttings',
            name='twit',
            field=models.CharField(default='', max_length=100, verbose_name='تویتر'),
        ),
    ]
