# Generated by Django 4.2.13 on 2024-11-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0005_ttings_address_ttings_facebook_ttings_insta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttings',
            name='address',
            field=models.CharField(default='taleqn', max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='email',
            field=models.EmailField(default='shams@gmail.com', max_length=254, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='facebook',
            field=models.CharField(default='facebook.com', max_length=100, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='insta',
            field=models.CharField(default='insta.com', max_length=100, verbose_name='انستاگرام'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='linkedin',
            field=models.CharField(default='linkedin.com', max_length=100, verbose_name='لینکدن'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='phone',
            field=models.CharField(default='05892590', max_length=20, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='twit',
            field=models.CharField(default='twit.com', max_length=100, verbose_name='تویتر'),
        ),
    ]
