# Generated by Django 4.2.13 on 2024-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0006_alter_ttings_address_alter_ttings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttings',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='facebook',
            field=models.CharField(max_length=100, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='insta',
            field=models.CharField(max_length=100, verbose_name='انستاگرام'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='linkedin',
            field=models.CharField(max_length=100, verbose_name='لینکدن'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='ttings',
            name='twit',
            field=models.CharField(max_length=100, verbose_name='تویتر'),
        ),
    ]
